In [58]:
import numpy as np
import pandas as pd

In [95]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
car_evaluation = fetch_ucirepo(id=19) 
  
# data (as pandas dataframes) 
X = car_evaluation.data.features 
y = car_evaluation.data.targets

class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]

In [60]:
from sklearn.model_selection import train_test_split

# data split, 70% training and 30% temp (temp = validation + test)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

# 30% temp data into 15% validation and 15% test
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [61]:
# from sklearn.metrics import confusion_matrix
# import numpy as np

# def calculate_metrics(y_true, y_pred):
#     acc_acc = acc_good = acc_unacc = acc_vgood = 0
#     good_acc = good_good = good_unacc = good_vgood = 0
#     unacc_acc = unacc_good = unacc_unacc = unacc_vgood = 0
#     vgood_acc = vgood_good = vgood_unacc = vgood_vgood = 0

#     y_true = y_true.to_numpy()
    
#     for i in range(len(y_true)):
#         actual = y_true[i]
#         predicted = y_pred[i]
        
#         if actual[0] and predicted[0]:
#             acc_acc += 1
#         elif actual[0] and predicted[1]:
#             acc_good += 1
#         elif actual[0] and predicted[2]:
#             acc_unacc += 1
#         elif actual[0] and predicted[3]:
#             acc_vgood += 1
#         elif actual[1] and predicted[0]:
#             good_acc += 1
#         elif actual[1] and predicted[1]:
#             good_good += 1
#         elif actual[1] and predicted[2]:
#             good_unacc += 1
#         elif actual[1] and predicted[3]:
#             good_vgood += 1
#         elif actual[2] and predicted[0]:
#             unacc_acc += 1
#         elif actual[2] and predicted[1]:
#             unacc_good += 1
#         elif actual[2] and predicted[2]:
#             unacc_unacc += 1
#         elif actual[2] and predicted[3]:
#             unacc_vgood += 1
#         elif actual[3] and predicted[0]:
#             vgood_acc += 1
#         elif actual[3] and predicted[1]:
#             vgood_good += 1
#         elif actual[3] and predicted[2]:
#             vgood_unacc += 1
#         elif actual[3] and predicted[3]:
#             vgood_vgood += 1

#     confusion_matrix = [
#         [acc_acc, acc_good, acc_unacc, acc_vgood],
#         [good_acc, good_good, good_unacc, good_vgood],
#         [unacc_acc, unacc_good, unacc_unacc, unacc_vgood],
#         [vgood_acc, vgood_good, vgood_unacc, vgood_vgood]
#     ]

#     # Accuracy
#     total_correct = acc_acc + good_good + unacc_unacc + vgood_vgood
#     total_predictions = sum(sum(row) for row in confusion_matrix)
#     accuracy = total_correct / total_predictions

#     # Precision calculations
#     if (acc_acc + good_acc + unacc_acc + vgood_acc) > 0:
#         Precision_of_acc = acc_acc / (acc_acc + good_acc + unacc_acc + vgood_acc)
#     else:
#         Precision_of_acc = 0

#     if (acc_good + good_good + unacc_good + vgood_good) > 0:
#         Precision_of_good = good_good / (acc_good + good_good + unacc_good + vgood_good)
#     else:
#         Precision_of_good = 0

#     if (acc_unacc + good_unacc + unacc_unacc + vgood_unacc) > 0:
#         Precision_of_unacc = unacc_unacc / (acc_unacc + good_unacc + unacc_unacc + vgood_unacc)
#     else:
#         Precision_of_unacc = 0

#     if (acc_vgood + good_vgood + unacc_vgood + vgood_vgood) > 0:
#         Precision_of_vgood = vgood_vgood / (acc_vgood + good_vgood + unacc_vgood + vgood_vgood)
#     else:
#         Precision_of_vgood = 0
        
#     # Precision_of_acc = acc_acc / (acc_acc + good_acc + unacc_acc + vgood_acc)
#     # Precision_of_good = good_good / (acc_good + good_good + unacc_good + vgood_good)
#     # Precision_of_unacc = unacc_unacc / (acc_unacc + good_unacc + unacc_unacc + vgood_unacc)
#     # Precision_of_vgood = vgood_vgood / (acc_vgood + good_vgood + unacc_vgood + vgood_vgood)
#     average_precision = (Precision_of_acc + Precision_of_good + Precision_of_unacc + Precision_of_vgood) / 4.0

#     # Recall calculations
#     if (acc_acc + acc_good + acc_unacc + acc_vgood) > 0:
#         Recall_of_acc = acc_acc / (acc_acc + acc_good + acc_unacc + acc_vgood)
#     else:
#         Recall_of_acc = 0

#     if (good_acc + good_good + good_unacc + good_vgood) > 0:
#         Recall_of_good = good_good / (good_acc + good_good + good_unacc + good_vgood)
#     else:
#         Recall_of_good = 0

#     if (unacc_acc + unacc_good + unacc_unacc + unacc_vgood) > 0:
#         Recall_of_unacc = unacc_unacc / (unacc_acc + unacc_good + unacc_unacc + unacc_vgood)
#     else:
#         Recall_of_unacc = 0

#     if (vgood_acc + vgood_good + vgood_unacc + vgood_vgood) > 0:
#          Recall_of_vgood = vgood_vgood / (vgood_acc + vgood_good + vgood_unacc + vgood_vgood)
#     else:
#         Recall_of_vgood = 0
        
#     # Recall_of_acc = acc_acc / (acc_acc + acc_good + acc_unacc + acc_vgood)
#     # Recall_of_good = good_good / (good_acc + good_good + good_unacc + good_vgood)
#     # Recall_of_unacc = unacc_unacc / (unacc_acc + unacc_good + unacc_unacc + unacc_vgood)
#     # Recall_of_vgood = vgood_vgood / (vgood_acc + vgood_good + vgood_unacc + vgood_vgood)
#     average_recall = (Recall_of_acc + Recall_of_good + Recall_of_unacc + Recall_of_vgood) / 4.0

#     # F1 Score
#     average_f1_score = 2 * ((average_precision * average_recall) / (average_precision + average_recall))

#     print("Confusion Matrix:")
#     for row in confusion_matrix:
#         print(row)

#     print(f"Accuracy: {accuracy}")
#     print(f"Average Precision: {average_precision}")
#     print(f"Average Recall: {average_recall}")
#     print(f"Average F1 Score: {average_f1_score}")

In [149]:
def calculate_metrics(y_true, y_pred):
    # Check if y_true is a pandas DataFrame and convert it to a NumPy array for compatibility
    if isinstance(y_true, pd.DataFrame):
        y_true = y_true.to_numpy()  # Convert y_true to a NumPy array

    # Check if y_pred is a pandas DataFrame and convert it to a NumPy array for compatibility
    if isinstance(y_pred, pd.DataFrame):
        y_pred = y_pred.to_numpy()  # Convert y_pred to a NumPy array

    # # Shape before flattening
    # print(y_true.shape)
    # print(y_pred.shape)
    
    y_true = y_true.flatten()
    y_pred = y_pred.flatten()
    
    # # Shape after flattening
    # print(y_true.shape)
    # print(y_pred.shape)

    # Find unique class names in y_true and determine the number of unique classes
    class_names = np.unique(y_true)  # Get unique class names from y_true
    unique_classes = class_names.size  # Count the number of unique classes

    # Initialize a confusion matrix with zeros, sized based on the number of unique classes
    confusion_matrix = np.zeros((unique_classes, unique_classes), dtype=int)

    # Map class names to indices for easy lookup
    class_name_to_index = {class_name: idx for idx, class_name in enumerate(class_names)}

    # Count occurrences of actual vs predicted labels
    for actual, predicted in zip(y_true, y_pred):
        # Ensure actual and predicted are scalar values, not arrays
        actual = actual.item() if isinstance(actual, np.ndarray) else actual
        predicted = predicted.item() if isinstance(predicted, np.ndarray) else predicted
        
        # Find the index for the actual and predicted class
        actual_index = class_name_to_index[actual]
        predicted_index = class_name_to_index[predicted]

        # Increment the appropriate cell in the confusion matrix
        confusion_matrix[actual_index, predicted_index] += 1

    # print(type(confusion_matrix))
    # print(confusion_matrix.shape)

    # Print the confusion matrix row by row
    for row in confusion_matrix:
        print(" ".join(map(str, row)))  # Print each row of the confusion matrix

In [63]:
print("Type of X_train:", type(X_train))
print("Shape of X_train:", X_train.shape)
print("Type of y_train:", type(y_train))
print("Shape of y_train:", y_train.shape)
print("Type of X_temp:", type(X_temp))
print("Shape of X_temp:", X_temp.shape)
print("Type of y_temp:", type(y_temp))
print("Shape of y_temp:", y_temp.shape)

Type of X_train: <class 'pandas.core.frame.DataFrame'>
Shape of X_train: (1209, 6)
Type of y_train: <class 'pandas.core.frame.DataFrame'>
Shape of y_train: (1209, 1)
Type of X_temp: <class 'pandas.core.frame.DataFrame'>
Shape of X_temp: (519, 6)
Type of y_temp: <class 'pandas.core.frame.DataFrame'>
Shape of y_temp: (519, 1)


**ZeroR** <br>
In a multiclass classification setting, ZeroR will look at the target values in the training data, count the frequencies of each class, and select the most frequent class as its prediction for all instances, regardless of the input features. <br>
ZeroR doesn't learn from input features, so it only needs the training data to calculate the most frequent class. There's no need to tune hyperparameters, so a validation set isn't required.

**ZeroR Model Implementation**  
This cell implements the ZeroR algorithm, which predicts the most frequent class from the training data, ignoring all feature information. It calculates the mode of the target variable (`y_train`) and uses this most frequent class to make predictions for the training, validation, and test sets. The accuracy of the model is then evaluated by comparing the predicted labels with the actual labels.

In [151]:
import numpy as np
from sklearn.metrics import accuracy_score

# Get the most frequent class from the training set
most_frequent_class = y_train.mode(axis=0).iloc[0]  # Get the most frequent class label

# Predict the most frequent class for all samples in the training, validation, and test sets
y_train_pred = np.full(y_train.shape[0], most_frequent_class)
y_val_pred = np.full(y_val.shape[0], most_frequent_class)
y_test_pred = np.full(y_test.shape[0], most_frequent_class)

# Calculate accuracy using the true labels and the predicted labels
train_accuracy = accuracy_score(y_train, y_train_pred)
val_accuracy = accuracy_score(y_val, y_val_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Print ZeroR model accuracy
print("ZeroR Model Accuracy:")
print("Training Accuracy:", train_accuracy)
print("Validation Accuracy:", val_accuracy)
print("Test Accuracy:", test_accuracy)

print("------------------------------")
print("Validation Set:")
calculate_metrics(y_val, y_val_pred)

print("------------------------------")
print("Test Set:")
calculate_metrics(y_test, y_test_pred)

ZeroR Model Accuracy:
Training Accuracy: 0.7047146401985112
Validation Accuracy: 0.6872586872586872
Test Accuracy: 0.6923076923076923
------------------------------
Validation Set:
0 0 57 0
0 0 10 0
0 0 178 0
0 0 14 0
------------------------------
Test Set:
0 0 61 0
0 0 9 0
0 0 180 0
0 0 10 0


In [75]:
# Initializing a confusion matrix of size unique_classes x unique_classes to store the results
unique_classes = 5    
confusion_matrix = np.zeros((unique_classes, unique_classes), dtype=int)

print(confusion_matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
